### ISSUE TITLE
N6vlanId Input in the parameters_file_single_ASE_AP5GC.xlsx

### ISSUE THREAD

**Issue by jkeyser-bats** [Azure/ASE_automation_for_AP5GC#1]
In the vlanid fields for the DNNs, the sheet says to leave blank if not in use.  This caused an error when attempting to run the script.  I had to place 0 in the fields.

**Comment by venkyswaminathan** [comment]
Yes, I faced the same issue

**Comment by msft-sgurung** [comment]
@sudeepgitgit it appears from commit cb461d39aab25d1c184c3ff3db5c1fd12af8d40c that this is addressed now?

**Comment by venkyswaminathan** [comment]
> @sudeepgitgit it appears from commit [cb461d3](https://github.com/Azure/ASE_automation_for_AP5GC/commit/cb461d39aab25d1c184c3ff3db5c1fd12af8d40c) that this is addressed now?

I ran this version (downloaded May 15th) and got the same error.

**Comment by sudeepgitgit** [comment]
hi @venkyswaminathan the new parameters file mentions to use 0 (and not blank) for a case where you don't want to use vlan tagging on the ASE. 
Are you having an issue after using 0 in the vlan field? 
Can you send me your error details?

**Comment by venkyswaminathan** [comment]
The rows 32 N2VlanId and 38 N3vlanId were blank and this error occured. The Description reads "Optional VLAN identifier for traffic on the N2 (S1-MME) Access network. Leave blank if not in use." and "Optional VLAN identifier for traffic on the N3 (S1-U) Access network. Leave blank if not in use." respectively.  
Get-DeviceConfigurationStatus response: {
    "deviceConfiguration":  {
                                "status":  "Complete",
                                "results":  [
                                                {
                                                    "declarationName":  "Network",
                                                    "resultCode":  "Failed",
                                                    "errorCode":  "RequiredPropertyMissing",
                                                    "message":  "Required property is missing at VirtualNetwork.VlanId"
                                                }
                                            ]
                            }
}
Device Configuration Results: {
    "declarationName":  "Network",
    "resultCode":  "Failed",
    "errorCode":  "RequiredPropertyMissing",
    "message":  "Required property is missing at VirtualNetwork.VlanId"
}
Unexpected resultcode for Network and Failed
At C:\Users\User.user-PC\Downloads\ASE_automation_for_AP5GC-main\ASE_automation_for_AP5GC-main\one_script_single_ASE.ps1:1569 char:21
+ ...             throw "Unexpected resultcode for $element and $resultCode ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unexpected resu...work and Failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Unexpected resultcode for Network and Failed

**Comment by venkyswaminathan** [comment]
> Yes, I faced the same issue

To clarify, the issue I encountered was when the vlanId for N2 and N3 were blank. The N6vlandDNN1 value was set to 0

**Comment by sudeepgitgit** [comment]
Hi @venkyswaminathan  this was a miss on my part between my local copy and the main repo copy of the parameters file. I've updated the parameters file description to clearly mention that using Blank is not allowed and that it needs to be 0 in case you don't plan on implementing vlan tagging on the ASE for N2, N3 (or N6) interfaces.
Thank you for reporting this.

**Comment by jkeyser-bats** [comment]
Thanks for the help Sudeep.  I ran the script the other day and it worked great!

Thanks,

Jared
